### PR TITLE
fix: only pointer rcvers for RoundRobinLoadBalancer

### PR DESCRIPTION
**Pull request by Nasfame**

### CODE REVIEW

**Comment by bxcodec** [comment]
I don't think this is possible without pointer, because we need to save the state so we can know which instance will be selected

**Comment by bxcodec** [comment]
Oh wait, this is for random policy

**Comment by bxcodec** [comment]
But it fails the test tho. Can u check, I think you have a test that need to save the state *by using pointer

**Comment by Nasfame** [comment]
> But it fails the test tho. Can u check, I think you have a test that need to save the state *by using pointer

its failing in linter

**Comment by Nasfame** [comment]
@bxcodec fixed the tests. While we are at it, once this is merged, make sure to increment the major version in the release tag.

Also , can u take a look at https://github.com/bxcodec/dbresolver/issues/35

**Pull request closed without merging**
