### PR TITLE
feat: upgrade the minimum go version

### PR DESCRIPTION
**Pull request by bxcodec**

### CODE REVIEW

**Review by Nasfame — DISMISSED** [review]
LGTM, FYI go1.20 is no longer supported with the release of go1.22

**Comment by bxcodec** [comment]
What are those test data? I saw you added it?

**Comment by Nasfame** [comment]
> What are those test data? I saw you added it?

testdata? not able to follow

**Comment by Nasfame** [comment]
what was the need to force push?

**Comment by Nasfame** [comment]
That's fuzz seed data for reproducibility

**Comment by Nasfame** [comment]
@bxcodec 

```
1599694a935139af681ea380560b405c360ebb4d is the first bad commit
commit 1599694a935139af681ea380560b405c360ebb4d
Author: Iman Tumorang <iman@tumorang.com>
Date:   Wed Feb 28 15:25:46 2024 +0700

    feat: upgrade the mimimum go version

 .golangci.yaml               |  2 ++
 Makefile                     |  3 ++-
 db.go                        |  2 +-
 go.mod                       |  6 +++---
 go.sum                       |  4 ++++
 loadbalancer.go              | 13 +++----------
 loadbalancer_test.go         |  2 +-
 misc/makefile/tools.Makefile | 18 +++++++++---------
 8 files changed, 25 insertions(+), 25 deletions(-)

```

**Comment by Nasfame** [comment]
@bxcodec Kindly revert `1599694a935139af681ea380560b405c360ebb4d` and cherrypick to a new branch.

**Comment by bxcodec** [comment]
Lol, it's the first commit. So it's failed even on the first commit

**Comment by bxcodec** [comment]
What is this automated commit for the fuzz tests? @Nasfame

**Pull request merged**
